apiVersion: v2
name: eventail
description: A call for papers and scheduling system for conferences
type: application
version: 0.0.0
home: https://github.com/eventail-scheduling/eventail-deploy
sources:
  - https://github.com/eventail-scheduling/eventail-deploy
  - https://github.com/eventail-scheduling/eventail-api
  - https://github.com/eventail-scheduling/eventail-web
