apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventail.fullname" . }}-api
  labels:
    {{- include "eventail.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "eventail.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
