apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventail.fullname" . }}-web
  labels:
    {{- include "eventail.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "eventail.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
