{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eventail.fullname" . }}-worker
  labels:
    {{- include "eventail.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "eventail.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "eventail.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- include "eventail.podSecurityContext" . | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          args: ["./worker.js"]
          env:
            {{- include "eventail.workerEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          securityContext:
            {{- include "eventail.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }}
