apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventail-furry-schedule-adapter.fullname" . }}
  labels:
    {{- include "eventail-furry-schedule-adapter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "eventail-furry-schedule-adapter.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
